// <auto-generated />
using System;
using DownloaderWeb.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DownloaderWeb.Migrations
{
    [DbContext(typeof(DownloadContext))]
    partial class DownloadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DownloaderWeb.DataLayer.Download", b =>
                {
                    b.Property<int>("DownloadId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<string>("FileType");

                    b.Property<int>("ParallelDownloads");

                    b.Property<long>("Size");

                    b.Property<string>("Status");

                    b.Property<TimeSpan>("TimeTaken");

                    b.Property<string>("downloadPercentage");

                    b.Property<string>("downloadUrl");

                    b.HasKey("DownloadId");

                    b.ToTable("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
